train_path: "/workspaces/confidence_localization/data/lab/data/processed/1spk_6pink_snr20dB_5ch/train/"
val_path: "/workspaces/confidence_localization/data/lab/data/processed/1spk_6pink_snr20dB_5ch/validation/"
test_path: "/workspaces/confidence_localization/data/lab/data/processed/1spk_6pink_snr20dB_5ch/test/"
rir_bank_path: "/workspaces/confidence_localization/data/lab/data/interim/rir_bank/"
target_path: "/workspaces/confidence_localization/data/lab/data/processed/1spk_6pink_snr20dB_5ch/target/"
wav_path: "/workspaces/confidence_localization/data/lab/data/raw/WSJ0_raw/"
log_dir: "/workspaces/confidence_localization/logs/DOAMAMBA"
save_dir: "/workspaces/confidence_localization/models/"

default_gpu : 6

resume_from_checkpoint: false

train_size : 5400
val_size : 600

batch_size: 8
num_workers: 8

preprocessed_data_flag : True

num_noise_sources : 6

pre_speech_noise_time : 2
max_num_of_speakers : 1
delete_all_samples_flag: False
sample_length_secs: 8
min_sep : 25
# possible_heights: [1.65, 1.675, 1.7, 1.725, 1.75, 1.775, 1.8, 1.825, 1.85]
# possible_heights: [1.75]
room_dim: [5, 5, 2.6]
receivers_coords:
  - [2.500, 2.500, 0.750]
  - [2.550, 2.500, 0.750]
  - [2.500, 2.550, 0.750]
  - [2.450, 2.500, 0.750] 
  - [2.500, 2.450, 0.750]   

J : 1 #amount of pink noise sources

src_height : 1.75

sound_velocity: 340
hop : 32
order : -1
beta : 0.34
nsample: 2048
p_silence: 0.0
p_one: 1
p_movement : 0.5
dominance_threshold : 0.6
min_overlap : 0.3
max_overlap : 0.9
snr_db : 20

recivers_num : 5

fs: 16000
nfft : 1024
win_len : 8
overlap : 0.75
exp_window_smoothing : 0.9

eps: 1e-6

input_dim : 1024
d_model : 4
freq_dim : 1024
time_dim : 376
hidden_dim : 64
conv_dim : 4
layers : [2, 4, 4, 4]
res_alpha : 0.1
log_var_weight : 1

lr : 5e-4
weight_decay: 1e-5
epochs: 300
regularization_constant : 1e-6
temporal_reg_factor : 1e-4

classification : False
logvar_confidence_on_noise: False
# nnl_func : 'von_mises'
nnl_func : 'gaussian'
error_bound_on_mse : 180


ar_coef : 0.9
ar_order : 1

initial_warmup : 0
warmup : 300

noise_beta : 0
