[project]
name = "confidence_localization"
version = "0.0.2"
description = "Sound source localization in the time-frequency domain with an added confidence score"
authors = [
  { name = "Adam Shusterman" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License"
]
requires-python = ">=3.10"